### ISSUE TITLE
The texture of Cole from example project is not shown

### ISSUE THREAD

**Issue by o-fedorov** [gagdiez/PACgd#2] opened 2021-09-28 14:30 UTC
Hi.

I tried to run the example projects.  The actions work well, also Cole is just a rectangle, there are no sprites and no animation is visible. See the screenshot attached.

I tried to play around with the Sprite3D options, reimport the `spritesheet.png`, it did not help.

I would really appreciate if you suggest how to make it visible.
<img width="1020" alt="Знімок екрана 2021-09-28 о 16 43 18" src="https://user-images.githubusercontent.com/2283679/135107590-0c1fe4c6-4e89-4f1c-bd26-8b2b0969a8d4.png">

**Comment by gagdiez** [comment] 2021-09-28 14:59
Hi @o-fedorov, thanks for getting interested in the project. I downloaded and tested importing all the examples now in Godot 3.2.2 and everything worked fine. Could you give me more information from your system?

Particularly:
- Operative System
- GODOT version you are using
- The URL to one of the repos that do not work (thought I think you are getting problems with all of them, no?)
-
Thanks!

**Comment by o-fedorov** [comment] 2021-09-29 06:47
- OS: macOS Big Sur v11.6 (Intel).
- Godot Engine v3.3.3.stable.official [b973f997f]
- The URL for the repos: all from the QuickStart documentation:
    - https://github.com/gagdiez/PACgd/archive/main.zip
    - https://github.com/gagdiez/PACgd_examples/archive/main.zip

I suppose the main difference is the version of Godot Engine. Let me try another one to figure this out.

**Comment by o-fedorov** [comment] 2021-09-29 16:46
I just checked. It does work in Godot 3.2.2, but starting from the next version (Godot 3.2.3) Cole becomes just a rectangle.

**Comment by gagdiez** [comment] 2021-09-30 09:21
Indeed, I checked and the problem is in the "materials" property of the Sprite. If you disable it, it goes back to normal. I guess they changed how the materials behave for 2d images. I will take a closer look later and fix all the examples. Thanks for finding the error!

**Comment by o-fedorov** [comment] 2021-09-30 09:27
This issue looks related: https://github.com/godotengine/godot/issues/33234

Here is how to fix the examples for Godot 3.2.3+:

First, select the Cole's sprite, click on "Texture" and copy the value of "Local Path".

Then follow these steps (see the screenshot):

1. Scroll down to `GeometryInstance`, click on `Geometry` -> `Material Override`.
2. Under `Albedo` select `Texture` -> `New StreamTexture`.
3. Paste the "Local Path" copied previously for the texture.

<img width="235" alt="Знімок екрана 2021-09-30 о 12 15 05" src="https://user-images.githubusercontent.com/2283679/135426287-de654bd1-ff26-45ed-9094-0b1570089661.png">

**Comment by gagdiez** [comment] 2021-10-11 09:51
Fixed on last commit, I simply removed the material override, will modify the other examples now. Thanks for the interest in the project! Any doubts you have or help you might need, do not hesitate in contacting me!

**Closed as completed by gagdiez** 2021-10-11 09:51 UTC
